# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6_BD/CORE-R6_BD.srcs/sources_1/ip/denise_colortable_ram_mf/denise_colortable_ram_mf.xci
# IP: The module: 'denise_colortable_ram_mf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6_BD/CORE-R6_BD.gen/sources_1/ip/denise_colortable_ram_mf/denise_colortable_ram_mf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'denise_colortable_ram_mf'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6_BD/CORE-R6_BD.srcs/sources_1/ip/denise_colortable_ram_mf/denise_colortable_ram_mf.xci
# IP: The module: 'denise_colortable_ram_mf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6_BD/CORE-R6_BD.gen/sources_1/ip/denise_colortable_ram_mf/denise_colortable_ram_mf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'denise_colortable_ram_mf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
