# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6.runs/synth_1/mega65_r6.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache C:/Users/david/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-17064-Retro-PC/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6.cache/wt [current_project]
set_property parent.project_path D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE-R6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set src_rc [catch { 
  puts "source D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/m2m-rom/synth_pre.tcl"
  source D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/m2m-rom/synth_pre.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 status "$_RESULT"
  send_msg_id runtcl-2 status "sourcing script D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/m2m-rom/synth_pre.tcl failed"
  return -code error
}
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/audio_out.v
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/MiSTer/csync.sv
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/MiSTer/hq2x.sv
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/MiSTer/iir_filter.v
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/MiSTer/scandoubler.v
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/MiSTer/video_freezer.sv
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/MiSTer/video_mixer.sv
}
read_vhdl -library xil_defaultlib D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/cycle_counter.vhd
read_vhdl -vhdl2008 -library xil_defaultlib {
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/tdp_ram.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/2port2clk_ram.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/2port2clk_ram_byteenable.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/EAE.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/cpu_constants.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/alu.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/alu_shifter.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/vga_recover_counters.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/ram_init.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/vga_osm.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/video_overlay.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/analog_pipeline.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/ascal.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/M65/audio.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/tools.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/video_modes_pkg.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/vhdl/globals.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/HDMI/types_pkg.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/cdc_stable.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/cdc_pulse.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/video_counters.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/crop.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/clk_synthetic_enable.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/memory/avm_decrease.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/HDMI/sync_reg.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/HDMI/hdmi_tx_encoder.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/HDMI/vga_to_hdmi.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/HDMI/serialiser_10to1_selectio.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/digital_pipeline.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/hdmi_flicker_free.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/av_pipeline/av_pipeline.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/memory/avm_arbit.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/memory/avm_arbit_general.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/memory/axi_fifo.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/memory/avm_fifo.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/basic_uart.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/QNICE/qnice_globals.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/block_ram.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/block_rom.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/bus_uart.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/byte_bram.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/vhdl/clk.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/clk_m2m.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/clock_counter.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/vhdl/config.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/i2c/cpu_to_i2c_master.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/debounce.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/debouncer.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/fifo.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/HDMI/video_out_clock.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/reset_manager.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/M65/kb_matrix_ram.vhdl
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/M65/mega65kbd_to_matrix.vhdl
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/M65/matrix_to_keynum.vhdl
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/m2m_keyb.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/qnice_cpu.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/QNICE/sdmux.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/sdcard.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/QNICE/qnice_mmio.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/QNICE/qnice.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/qnice2hyperram.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/M65/mouse_input.vhdl
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/qnice_wrapper.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/hyperram/hyperram_errata.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/hyperram/hyperram_config.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/hyperram/hyperram_ctrl.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/hyperram/hyperram_fifo.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/hyperram/hyperram_rx.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/hyperram/hyperram_tx.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/controllers/hyperram/hyperram.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/i2c/rtc_master.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/i2c/rtc_controller.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/qnice_arbit.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/i2c/i2c_master.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/i2c/i2c_controller.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/i2c/rtc_wrapper.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/framework.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/vhdl/keyboard.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/vhdl/main.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/vdrives.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/vhdl/mega65.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/register_file.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/QNICE/vhdl/sd_spi.vhd
  D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/vhdl/top_mega65-r6.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/MEGA65-R6.xdc
set_property used_in_implementation false [get_files D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/MEGA65-R6.xdc]

read_xdc D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/common.xdc
set_property used_in_implementation false [get_files D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/M2M/common.xdc]

read_xdc D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE.xdc
set_property used_in_implementation false [get_files D:/Retro/Mega65/FPGA_Projects/Amiga-Core-Test/CORE/CORE.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mega65_r6 -part xc7a200tfbg484-2 -flatten_hierarchy none
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mega65_r6.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file mega65_r6_utilization_synth.rpt -pb mega65_r6_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
